### ISSUE TITLE
[q]Autoload with dependencies

### ISSUE THREAD

**Issue by SkeLLLa** [fastify/fastify-autoload#31]
Fastify plugin module support dependencies section. If some plugins wrapped with fastify-plugin registered through autoload, then it checks only plugins, that are loaded through autoload. However it ignores plugins that are previously loaded with fastify.register.

Is that correct behaviour? Or it should check `Symbol(registered-plugin)` in fastify instance as well?

**Comment by mcollina** [comment]
Can you make an example where this behavior is failing you? How would you change this?

**Comment by SkeLLLa** [comment]
@mcollina 
Consider we have the following structure

```js
const fastify = require('fastify')();
const externalPlugin = require('fastify-external-plugin);
const autoloadPlugin = require('fastify-autoload');
fastify.register(externalPlugin);
fastify.register(autoloadPlugin, {dir: './plugins'});

... // await for fastify.ready and listen
```
As an fastify-external-plugin we could have `fastify-mongo` plugin, for example, and couple of own custom plugins are loaded through autoload plugin from plugins dir. Our own plugins depend or use functionality from `fastify-mongo` module. So in that case we should define dependency on `fastify-mongo` module. And now fastify-autoload plugin will search that module inside directory provided in options, but it will not check modules registered through `fastify.register` function.

Obviously we can set dependency to decorators and wait until `fastify.mongo` decorator will be available. However I think there could be a case when our custom plugins could depend on some other plugin that doesn't decorate fastify instance.

**Comment by mcollina** [comment]
Fastify does not resolve the dependency graph, because plugins are loaded in-order by fastify. This plugin needs that, because it would load them from the order that they are being returned from the file system.

Essentially, the dependency order thing is _needed_ to solve a problem added by autoload, and only on plugins registered by autoload.

If you need `fastify.mongo` _before_ the plugins returned by autoload, then register it before then. Maybe I'm not really understanding your issue. Would you mind crafting a little repo?

**Comment by salmanm** [comment]
I realise what @SkeLLLa means is if we have a plugin as 

```js
const fp = require('fastify-plugin')

function plugin (f, opts, next) {
  // plugin body

  next()
}

module.exports = fp(plugin, {
  name: 'plugin-g',
  dependencies: ['fastify-sensible']
})
```

The new feature of automatically resolving dependencies won't find `fastify-sensible` in the list of available plugins, because its being `register`ed manually.

The problem sounds legit. Do you have any suggestion on how to tackle this? @mcollina

**Comment by mcollina** [comment]
I think the best suggestion if a plugin is missing is to assume that is loaded by fastify and rely on https://github.com/fastify/fastify/blob/e2062efcc7adbb82101e3afd7734835f81d71bbe/lib/pluginUtils.js#L29 this check. It will throw if it's missing, and that's ok.

**Comment by salmanm** [comment]
Yea that sounds good. Something like this? https://github.com/fastify/fastify-autoload/pull/32
